[project]
name = "logger-1.0.6"
description = "Simple Logger inspired by the Logger base module of python"
version = "1.0.6"
authors = [
    { name = "Malo Boucé" }
]
dependencies = [
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"